name: EtumEconomy
version: '${project.version}'
main: net.etum.etumeconomy.Main
api-version: '1.20'
description: Manage player economy in your server with EtumEconomy.
author: JanjeVuk
website: 'https://example.com'
commands:
  eco:
    description: Main command for EtumEconomy
    usage: /<command> [args]
    permission: etumeconomy.command.eco
    aliases:
      - economy
permissions:
  etumeconomy.command.eco:
    description: Allows access to the main EtumEconomy command
    default: op
